{{- /* microservice deployment */}}

apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}
  namespace: {{ .Release.Namespace }}
  labels:
    component: primary
  {{- include "app.labels" . | indent 4 }}
spec:
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: {{ .Values.deployment.rolloutSurge }}
      maxUnavailable: {{ .Values.deployment.rolloutUnavailable }}
  selector:
    matchLabels:
      app: {{ .Release.Name }}
      component: primary
  replicas: {{ .Values.autoscaling.min_replicas }}
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}
        component: primary
        {{- include "app.labels" . | nindent 8 }}
      annotations:
      {{- include "common.annotations" . | nindent 8 }}
    spec:
      serviceAccountName: {{ default (include "appname" .) .Values.serviceAccount }}
      nodeSelector:
        iam.gke.io/gke-metadata-server-enabled: "true"
        {{- range $key,$value:= index .Values "deployment" "nodeSelector" }}
        {{ $key }}: {{ tpl ($value | toString) $ | quote }}
        {{- end }}
      containers:
        - name: {{ .Release.Name }}
          image: {{ printf "%s:%s" .Values.image .Values.image_tag }}
          imagePullPolicy: {{ .Values.imagePullPolicy }}
          env:
            - name: HANDLE_BROKER_MESSAGES
              value: {{ .Values.worker.enabled | ternary "false" (.Values.parameters.HANDLE_BROKER_MESSAGES | default "false") | quote }}
            - name: APP
              value: {{ .Release.Name }}
            - name: ENV
              value: {{ .Values.global.env }}
            {{- range $key, $value := .Values.parameters }}
            {{- if ne $key "HANDLE_BROKER_MESSAGES" }}
            - name: {{ upper $key | replace "-" "_" }}
              value: {{ tpl ($value | toString) $ | quote }}
            {{- end }}
            {{- end }}
            {{- range $secret := .Values.secrets }}
            - name: {{ upper $secret }}
              valueFrom:
                secretKeyRef:
                  name: {{ $secret | replace "_" "-" }}
                  key: value
                  optional: false
            {{- end }}
        {{- if or .Values.service.internalPort (and (eq .Values.debug.enabled true) .Values.debug.port) }}
          ports:
        {{- end }}
        {{- if .Values.service.internalPort }}
          - containerPort: {{ .Values.service.internalPort }}
        {{- end }}
        {{- if and (eq .Values.debug.enabled true) .Values.debug.port }}
          - containerPort: {{ .Values.debug.port }}
        {{- end }}
      {{- if .Values.probeConfig }}
        {{- if .Values.startupProbe }}
          startupProbe: {{- toYaml .Values.probeConfig | nindent 12 }} {{- toYaml .Values.startupProbe | nindent 12 }}
        {{- end }}
        {{- if .Values.livenessProbe }}
          livenessProbe: {{- toYaml .Values.probeConfig | nindent 12 }} {{- toYaml .Values.livenessProbe | nindent 12 }}
        {{- end }}
        {{- if .Values.readinessProbe }}
          readinessProbe: {{- toYaml .Values.probeConfig | nindent 12 }} {{- toYaml .Values.readinessProbe | nindent 12 }}
        {{- end }}
      {{- end }}
        {{- if ne .Values.debug.enabled true }}
          resources:
            requests:
              cpu: {{ .Values.autoscaling.min_cpu }}
              memory: {{ .Values.autoscaling.min_memory }}
            limits:
            {{- if .Values.autoscaling.max_cpu }}
              cpu: {{ .Values.autoscaling.max_cpu }}
            {{- end }}
              memory: {{ .Values.autoscaling.max_memory }}
        {{- end }}
        {{- if eq .Values.debug.enabled true }}
          command: {{ mustRegexSplit " +" .Values.debug.command -1 | toJson }}

        {{- end }}
          env:
            - name: APP
              value: {{ .Release.Name }}
            - name: ENV
              value: {{ .Values.global.env }}

            #Range below is for environment variables
            {{- range $key,$value:= .Values.parameters }}
            - name: {{ upper $key | replace "-" "_" }}
              value: {{ tpl ($value | toString) $ | quote }}
            {{- end }}

            #Range below is for secrets
            {{- range $secret := .Values.secrets }}
            - name: {{ upper $secret }}
              valueFrom:
                secretKeyRef:
                  name: {{ $secret | replace "_" "-" }}
                  key: value
                  optional: false
            {{- end }}

          volumeMounts:
            - name: gcp-secret-store-vol
              mountPath: "/var/secrets-store"
    {{- if eq .Values.init_container.enabled true }}
      initContainers:
        - name: {{ .Release.Name }}-init-script
          image: {{ printf "%s:%s" .Values.image .Values.image_tag }}
          imagePullPolicy: {{ .Values.imagePullPolicy }}
          command:
            {{ range $arg:= .Values.init_container.command }}
            - {{$arg | quote}}
            {{- end }}
          env:
            - name: APP
              value: {{ .Release.Name }}
            - name: ENV
              value: {{ .Values.global.env }}

            #Range below is for environment variables
            {{- range $key,$value:= .Values.parameters }}
            - name: {{ upper $key | replace "-" "_" }}
              value: {{ tpl ($value | toString) $ | quote }}
            {{- end }}

            #Range below is for secrets
            {{- range $secret := .Values.secrets }}
            - name: {{ upper $secret }}
              valueFrom:
                secretKeyRef:
                  name: {{ $secret | replace "_" "-" }}
                  key: value
                  optional: false
            {{- end }}
          volumeMounts:
            - name: gcp-secret-store-vol
              mountPath: "/var/secrets-store"
    {{- end }}
      volumes:
        - name: gcp-secret-store-vol
          csi:
            driver: secrets-store.csi.k8s.io
            readOnly: true
            volumeAttributes:
              secretProviderClass: {{ printf "gcp-secrets-%s" (include "appname" .)}}
---
{{- if .Values.worker.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-worker
  namespace: {{ .Release.Namespace }}
  labels:
    component: worker
    tags.datadoghq.com/service: {{ .Release.Name }}-worker
    {{- include "app.labels" . | nindent 4 }}
spec:
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: {{ .Values.deployment.rolloutSurge }}
      maxUnavailable: {{ .Values.deployment.rolloutUnavailable }}
  selector:
    matchLabels:
      app: {{ .Release.Name }}
      component: worker
  replicas: {{ .Values.worker.autoscaling.min_replicas | default .Values.autoscaling.min_replicas }}
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}
        component: worker
        tags.datadoghq.com/service: {{ .Release.Name }}-worker
        {{- include "app.labels" . | nindent 8 }}
      annotations:
        {{- include "common.annotations" (dict "root" . "componentName" (printf "%s-worker" .Release.Name)) | nindent 8 }}
    spec:
      serviceAccountName: {{ default (include "appname" .) .Values.serviceAccount }}
      # ... (nodeSelector for worker)
      containers:
        - name: {{ .Release.Name }}-worker
          image: {{ printf "%s:%s" .Values.image .Values.image_tag }}
          imagePullPolicy: {{ .Values.imagePullPolicy }}
          env:
            - name: HANDLE_BROKER_MESSAGES
              value: "true"
            - name: APP
              value: {{ .Release.Name }}-worker
            - name: ENV
              value: {{ .Values.global.env }}
            {{- range $key, $value := .Values.parameters }}
            {{- if ne $key "HANDLE_BROKER_MESSAGES" }}
            - name: {{ upper $key | replace "-" "_" }}
              value: {{ tpl ($value | toString) $ | quote }}
            {{- end }}
            {{- end }}
            {{- range $key, $value := .Values.worker.parameters }}
            {{- if ne $key "HANDLE_BROKER_MESSAGES" }}
            - name: {{ upper $key | replace "-" "_" }}
              value: {{ tpl ($value | toString) $ | quote }}
            {{- end }}
            {{- end }}
                    volumeMounts:
            - name: gcp-secret-store-vol
              mountPath: "/var/secrets-store"
    {{- end }}
      volumes:
        - name: gcp-secret-store-vol
          csi:
            driver: secrets-store.csi.k8s.io
            readOnly: true
            volumeAttributes:
              secretProviderClass: {{ printf "gcp-secrets-%s" (include "appname" .)}}

