{{- if .Values.linked_service.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.linked_service.name }}
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ .Values.linked_service.name }}
{{ include "linked_service.labels" $ | nindent 4 }}
spec:
  selector:
    app: {{ .Values.linked_service.name }}
  ports:
    {{- range $port := .Values.linked_service.parameters.ports }}
    - protocol: TCP
      port: {{ $port.containerPort }}
      targetPort: {{ $port.containerPort }}
    {{- end }}
{{- end }}

{{- range $svc := .Values.linked_services }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ $svc.name }}
  namespace: {{ $.Release.Namespace }}
  labels:
    app: {{ $svc.name }}
{{ include "linked_services.labels" (dict "name" $svc.name "ctx" $) | nindent 4 }}
spec:
  selector:
    app: {{ $svc.name }}
  ports:
    {{- range $port := $svc.parameters.ports }}
    - protocol: TCP
      port: {{ $port.containerPort }}
      targetPort: {{ $port.containerPort }}
    {{- end }}
{{- end }}
