{{- if .Values.linked_service.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.linked_service.name }}
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ .Values.linked_service.name }}
{{ include "linked_service.labels" $ | nindent 4 }}
  annotations:
{{ include "linked_service.annotations" $ | nindent 4 }}
spec:
  selector:
    matchLabels:
      app: {{ .Values.linked_service.name }}
  replicas: {{ .Values.linked_service.parameters.replicas }}
  template:
    metadata:
      labels:
        app: {{ .Values.linked_service.name }}
{{ include "linked_service.labels" $ | nindent 8 }}
      annotations:
{{ include "linked_service.annotations" $ | nindent 8 }}
    spec:
      serviceAccountName: {{ .Values.linked_service.parameters.serviceAccountName }}
      containers:
        - name: {{ .Values.linked_service.name }}
          image: {{ printf "%s:%s" .Values.linked_service.parameters.image.repository .Values.linked_service.parameters.image.tag }}
          ports:
            {{- range $port := .Values.linked_service.parameters.ports }}
            - containerPort: {{ $port.containerPort }}
            {{- end }}
          resources:
            requests:
              memory: {{ .Values.linked_service.parameters.resources.min_memory }}
              cpu: {{ .Values.linked_service.parameters.resources.min_cpu }}
            limits:
              memory: {{ .Values.linked_service.parameters.resources.max_memory }}
              cpu: {{ .Values.linked_service.parameters.resources.max_cpu }}
          env:
            {{- range $key, $value := .Values.linked_service.parameters.env }}
            - name: {{ $key }}
              value: {{ $value | quote }}
            {{- end }}
            {{- range $secret := .Values.linked_service.parameters.secrets }}
            - name: {{ upper $secret }}
              valueFrom:
                secretKeyRef:
                  name: {{ $secret | replace "_" "-" }}
                  key: value
                  optional: false
            {{- end }}
          volumeMounts:
            - name: gcp-secret-store-vol
              mountPath: "/var/secrets-store"
      volumes:
        - name: gcp-secret-store-vol
          csi:
            driver: secrets-store.csi.k8s.io
            readOnly: true
            volumeAttributes:
              secretProviderClass: {{ printf "gcp-secrets-%s" (include "appname" .)}}
{{- end }}
