{{- if .Values.microservice.linked_service.enabled }}
{{- range $svc := .Values.microservice.linked_service.services }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ $svc.name }}
  namespace: {{ $.Release.Namespace }}
  {{- include "app.labels" . | indent 2 }}
  {{- include "common.annotations" . | indent 2 }}
spec:
  selector:
    matchLabels:
      app: {{ $svc.name }}
  replicas: {{ $svc.parameters.replicas }}
  template:
    metadata:
        {{- include "app.labels" . | indent 6 }}
        app: {{ $svc.name }}
        {{- include "common.annotations" . | indent 6 }}
    spec:
      serviceAccountName: {{ $svc.parameters.serviceAccountName }}
      containers:
        - name: {{ $svc.name }}
          image: {{ printf "%s:%s" $svc.parameters.image.repository $svc.parameters.image.tag }}
          ports:
            {{- range $port := $svc.parameters.ports }}
            - containerPort: {{ $port.containerPort }}
            {{- end }}
          resources:
            requests:
              memory: {{ $svc.parameters.resources.min_memory }}
              cpu: {{ $svc.parameters.resources.min_cpu }}
            limits:
              memory: {{ $svc.parameters.resources.max_memory }}
              cpu: {{ $svc.parameters.resources.max_cpu }}
            #Range below is for environment variables
            {{- range $key,$value:= $svc.parameters.env }}
            - name: {{ $key }}
              value: {{ $value | quote }}
            {{- end }}
            #Range below is for secrets
            {{- range $secret := $svc.parameters.secrets }}
            - name: {{ $secret }}
              valueFrom:
                secretKeyRef:
                  name: {{ $secret | replace "_" "-" }}
                  key: value
                  optional: false
            {{- end }}
          volumeMounts:
            - name: gcp-secret-store-vol
              mountPath: "/var/secrets-store"
      volumes:
        - name: gcp-secret-store-vol
          csi:
            driver: secrets-store.csi.k8s.io
            readOnly: true
            volumeAttributes:
              secretProviderClass: {{ printf "gcp-secrets-%s" $svc.name }}
{{- end }}
{{- end }}
