apiVersion: autoscaling.gke.io/v1beta1
kind: MultidimPodAutoscaler
metadata:
  name: {{ printf "mpa-%s" .Release.Name }}
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ include "appname" . }}
  goals:
    metrics:
    - type: Resource
      resource:
      # Define the target CPU utilization request here
        name: cpu
        target:
          type: Utilization
          averageUtilization: {{ .Values.cpu_percentage_trigger }}
  constraints:
    global:
      minReplicas: {{ .Values.min_replicas }}
      maxReplicas: {{ .Values.max_replicas }}
    containerControlledResources: [ memory ]
    container:
    - name: '*'
    # Define boundaries for the memory request here
      requests:
        minAllowed:
          memory: {{ .Values.min_memory }}
        maxAllowed:
          memory: {{ .Values.max_memory }}
  policy:
    updateMode: Auto