{{- if ne .Values.migration.run_only_migration true }}
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ printf "pdb-%s" .Release.Name }}
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app: {{ include "appname" . }}
{{- end }}