apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ printf "pdb-%s" .Release.Name }}
spec:
  minAvailable: {{ if eq .Release.Namespace "stage0" }}1{{ else }}{{ if (hasKey .Values "pdbMinAvailable") }}{{ .Values.pdbMinAvailable }}{{ else }}1{{ end }}{{ end }}
  selector:
    matchLabels:
      app: {{ include "appname" . }}
---
{{- if (hasKey .Values "worker") }}
{{- if (and (hasKey .Values.worker "enabled") .Values.worker.enabled) }}
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ .Release.Name }}-worker-pdb
spec:
  selector:
    matchLabels:
      app: {{ .Release.Name }}-worker
{{- end }}
{{- end }}