apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: {{ printf "gcp-secrets-%s" (include "appname" .)}}
  {{- include "secrets.annotations" . | indent 2 }} 
spec:
  provider: gcp # accepted provider options: azure or vault or gcp
  parameters:
    auth: pod-adc ## refer to https://github.com/GoogleCloudPlatform/secrets-store-csi-driver-provider-gcp/blob/main/docs/authentication.md
    secrets: |

      {{- range $secret := .Values.secrets }}
      - resourceName: {{ printf "projects/%s/secrets/%s/versions/latest" $.Values.global.project_id $secret }}
        path: {{ $secret | replace "_" "-" | quote }}
      {{- end }}
  secretObjects:
    {{- range $secret := .Values.secrets }}
    - secretName: {{ $secret | replace "_" "-" }}
      type: Opaque
      data:
      - objectName: {{ $secret | replace "_" "-" | quote }}
        key: value
    {{- end }}
---
{{- if .Values.linked_service.enabled }}
apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: {{ printf "gcp-secrets-%s" .Values.linked_service.name }}
spec:
  provider: gcp # accepted provider options: azure or vault or gcp
  parameters:
    auth: pod-adc ## refer to https://github.com/GoogleCloudPlatform/secrets-store-csi-driver-provider-gcp/blob/main/docs/authentication.md
    secrets: |

      {{- range $secret := .Values.linked_service.parameters.secrets }}
      - resourceName: {{ printf "projects/%s/secrets/%s/versions/latest" $.Values.global.project_id $secret }}
        path: {{ $secret | replace "_" "-" | quote }}
      {{- end }}
  secretObjects:
    {{- range $secret := .Values.linked_service.parameters.secrets }}
    - secretName: {{ $secret | replace "_" "-" }}
      type: Opaque
      data:
      - objectName: {{ $secret | replace "_" "-" | quote }}
        key: value
    {{- end }}
{{- end }}
